import { Lottory } from "./Lottory";

export const lottory: Lottory[] = [
    {
        id: 1,
        path: "/",
        imageName: "img",
        extension: "jpg",
        title: "123456",
        number: {
            oneDigit: 1,
            twoDigit: 12,
            threeDigit: 123,
            fourDigit: 1234,
            fiveDigit: 12345,
            sixDigit: 123456,
            frontThreeDigit: 123,
            behindThreeDigit: 456,
            behindTwoDigit: 56,
        },
        time: "01-06-2021",
        amount: 1,
        price: 80,
        note: "asd",
    },
    {
        id: 2,
        path: "/",
        imageName: "img",
        extension: "jpg",
        title: "111111",
        number: {
            oneDigit: 1,
            twoDigit: 11,
            threeDigit: 111,
            fourDigit: 1111,
            fiveDigit: 11111,
            sixDigit: 111111,
            frontThreeDigit: 111,
            behindThreeDigit: 111,
            behindTwoDigit: 11,
        },
        time: "01-06-2021",
        amount: 1,
        price: 100,
        note: "asd",
    },
    {
        id: 3,
        path: "/",
        imageName: "img",
        extension: "jpg",
        title: "444444",
        number: {
            oneDigit: 4,
            twoDigit: 44,
            threeDigit: 444,
            fourDigit: 4444,
            fiveDigit: 44444,
            sixDigit: 444444,
            frontThreeDigit: 444,
            behindThreeDigit: 444,
            behindTwoDigit: 44,
        },
        time: "01-06-2021",
        amount: 1,
        price: 100,
        note: "asd",
    },
];
